# Generated by Django 3.2 on 2023-05-02 15:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSightsEventsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='ModelVillages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('images', models.ImageField(blank=True, null=True, upload_to='sights_media_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='sights_media_videos/%Y/%m/%d/', verbose_name='Видео')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelsightseventscategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'деревня',
                'verbose_name_plural': 'деревни',
            },
        ),
        migrations.CreateModel(
            name='ModelSights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('images', models.ImageField(blank=True, null=True, upload_to='sights_media_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='sights_media_videos/%Y/%m/%d/', verbose_name='Видео')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelsightseventscategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'достопримечательность',
                'verbose_name_plural': 'достопримечательности',
            },
        ),
        migrations.CreateModel(
            name='ModelEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('images', models.ImageField(blank=True, null=True, upload_to='events_media_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='events_media_videos/%Y/%m/%d/', verbose_name='Видео')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('sights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelsights', verbose_name='Достопримечательность')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelvillages', verbose_name='Достопримечательность')),
            ],
        ),
    ]
