# Generated by Django 3.2 on 2023-04-06 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SightsCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'категорию',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Sights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('images', models.ImageField(blank=True, null=True, upload_to='sights_media_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='sights_media_videos/%Y/%m/%d/', verbose_name='Видео')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sightscategories', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'достопримечательность',
                'verbose_name_plural': 'достопримечательности',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата')),
                ('images', models.ImageField(blank=True, null=True, upload_to='events_media_images/%Y/%m/%d/', verbose_name='Изображение')),
                ('video', models.FileField(blank=True, null=True, upload_to='events_media_videos/%Y/%m/%d/', verbose_name='Видео')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('sights', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sights', verbose_name='Достопримечательность')),
            ],
            options={
                'verbose_name': 'событие',
                'verbose_name_plural': 'события',
            },
        ),
    ]
