# Generated by Django 3.2 on 2023-05-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelevents',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
