# Generated by Django 3.2 on 2023-05-03 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marker',
            options={'verbose_name': 'точка на карте', 'verbose_name_plural': 'точки на карте'},
        ),
        migrations.RemoveField(
            model_name='modelsights',
            name='video',
        ),
        migrations.RemoveField(
            model_name='modelvillages',
            name='video',
        ),
        migrations.AlterField(
            model_name='marker',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelvillages', verbose_name='Точки на карте'),
        ),
    ]
