# Generated by Django 3.2.4 on 2023-06-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvillages',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='draft'),
        ),
    ]
