# Generated by Django 3.2 on 2023-04-25 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelsightsimage',
            name='sight',
        ),
        migrations.AddField(
            model_name='modelevents',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='events_media_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='modelsights',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='sights_media_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.DeleteModel(
            name='ModelEventsImage',
        ),
        migrations.DeleteModel(
            name='ModelSightsImage',
        ),
    ]
