# Generated by Django 3.2 on 2023-05-03 13:18

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0002_auto_20230503_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelsights',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='marker',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modelsights',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='villages_media_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='VillagesImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(default=1, null=True)),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('content_type', models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.modelvillages', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Фото к деревне',
                'verbose_name_plural': 'Фото к деревням',
            },
        ),
        migrations.CreateModel(
            name='EventsVideoSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(null=True)),
                ('video', models.FileField(upload_to='media/%Y/%m/%d/')),
                ('content_type', models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.modelevents', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Видео к статье',
                'verbose_name_plural': 'Видео к статьям',
            },
        ),
        migrations.CreateModel(
            name='EventsImageSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(default=1, null=True)),
                ('image', models.ImageField(upload_to='media/%Y/%m/%d/')),
                ('content_type', models.ForeignKey(default=20, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.modelevents', verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Фото к событию',
                'verbose_name_plural': 'Фото к событиям',
            },
        ),
    ]
