# Generated by Django 3.2 on 2023-05-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20230503_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelevents',
            name='images',
        ),
        migrations.RemoveField(
            model_name='modelevents',
            name='video',
        ),
        migrations.RemoveField(
            model_name='modelvillages',
            name='images',
        ),
        migrations.AddField(
            model_name='modelvillages',
            name='сover',
            field=models.ImageField(blank=True, null=True, upload_to='villages_media_covers/%Y/%m/%d/', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='eventsimageset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events_media_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='eventsvideoset',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='events_media_videos/%Y/%m/%d/', verbose_name='Видео'),
        ),
        migrations.AlterField(
            model_name='villagesimageset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='villages_media_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
