# Generated by Django 3.2 on 2023-05-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230503_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelvillages',
            old_name='сover',
            new_name='cover',
        ),
    ]
