# Generated by Django 3.2 on 2023-05-16 10:43

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('main', '0005_rename_sights_modelevents_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsimageset',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='eventsimageset',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='eventsimageset',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Ссылка на видео в youtube'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelvillages', verbose_name='Деревня'),
        ),
    ]
