# Generated by Django 3.2 on 2023-05-22 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230516_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelvillages',
            name='stone_inscription',
            field=models.ImageField(blank=True, null=True, upload_to='villages_media_stone_inscriptions/%Y/%m/%d/', verbose_name='Обложка'),
        ),
    ]
