# Generated by Django 3.2 on 2023-05-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_modelvillages_stone_inscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelvillages',
            name='stone_inscription',
            field=models.ImageField(blank=True, null=True, upload_to='villages_media_stone_inscriptions/%Y/%m/%d/', verbose_name='Каменная надпись'),
        ),
    ]
