# Generated by Django 3.2.4 on 2023-05-24 10:47

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230523_1124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsimageset',
            options={'verbose_name': 'image for event', 'verbose_name_plural': 'images for event'},
        ),
        migrations.AlterModelOptions(
            name='marker',
            options={'verbose_name': 'point on map', 'verbose_name_plural': 'points on map'},
        ),
        migrations.AlterModelOptions(
            name='modelevents',
            options={'verbose_name': 'event name', 'verbose_name_plural': 'events name'},
        ),
        migrations.AlterModelOptions(
            name='modelsights',
            options={'verbose_name': 'sight', 'verbose_name_plural': 'sights'},
        ),
        migrations.AlterModelOptions(
            name='modelsightseventscategories',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='modelvillages',
            options={'verbose_name': 'village', 'verbose_name_plural': 'villages'},
        ),
        migrations.AlterModelOptions(
            name='villagesimageset',
            options={'verbose_name': 'image for village', 'verbose_name_plural': 'images for village'},
        ),
        migrations.AddField(
            model_name='eventsimageset',
            name='image_en',
            field=models.ImageField(blank=True, null=True, upload_to='events_media_images/%Y/%m/%d/', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='eventsimageset',
            name='image_ru',
            field=models.ImageField(blank=True, null=True, upload_to='events_media_images/%Y/%m/%d/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='eventsimageset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='events_media_images/%Y/%m/%d/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='eventsimageset',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.modelevents', verbose_name='post'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelvillages', verbose_name='point on map'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='draft'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time create'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='youtube video url'),
        ),
        migrations.AlterField(
            model_name='modelevents',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelvillages', verbose_name='village'),
        ),
        migrations.AlterField(
            model_name='modelsights',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelsightseventscategories', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='modelsights',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelsights',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelsights',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelsights',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sights_media_images/%Y/%m/%d/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='modelsights',
            name='name',
            field=models.CharField(max_length=127, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelsights',
            name='name_en',
            field=models.CharField(max_length=127, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelsights',
            name='name_ru',
            field=models.CharField(max_length=127, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelsights',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time create'),
        ),
        migrations.AlterField(
            model_name='modelsightseventscategories',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelsightseventscategories',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelsightseventscategories',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelsightseventscategories',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelsightseventscategories',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelsightseventscategories',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.modelsightseventscategories', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='villages_media_covers/%Y/%m/%d/', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='description_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='description_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='name',
            field=models.CharField(max_length=127, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='name_en',
            field=models.CharField(max_length=127, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='name_ru',
            field=models.CharField(max_length=127, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='stone_inscription',
            field=models.ImageField(blank=True, null=True, upload_to='villages_media_stone_inscriptions/%Y/%m/%d/', verbose_name='stone inscription'),
        ),
        migrations.AlterField(
            model_name='modelvillages',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='time create'),
        ),
        migrations.AlterField(
            model_name='villagesimageset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='villages_media_images/%Y/%m/%d/', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='villagesimageset',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.modelvillages', verbose_name='post'),
        ),
    ]
