# Generated by Django 3.2.4 on 2023-05-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230524_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsimageset',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='eventsimageset',
            name='image_ru',
        ),
    ]
