# Generated by Django 3.2.4 on 2023-05-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20230524_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelevents',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterField(
            model_name='eventsimageset',
            name='object_id',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
